### PR TITLE
Ignore null warning to make the test pass

### PR DESCRIPTION
**Pull request by fromAtoZ**

### CODE REVIEW

**Comment by fromAtoZ** [comment]
@MoJRen @Kelcey @nscharfe

**Comment by MoJRen** [comment]
lgtm

we should eventually update this fork with latest master

**Comment by MoJRen** [comment]
please remember to update the submodule pointer on mopub-ios after this

**Comment by fromAtoZ** [comment]
There are some issues the latest master. I'll update the submodule pointer.

**Pull request merged**
